from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^showdata/', views.signup),
    url(r'^signup/', views.signup),
    url(r'^investor_view/', views.investor),
    url(r'^home/', views.investor, name='home'),
    url(r'^new/', views.report, name='report'),
    url(r'^company_page/', views.company_page, name='company_page'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^edit/', views.edit_company, name='edit_company'),
    url(r'^edit_report/', views.edit_report, name='edit_report'),
    url(r'^delete_report/', views.delete_report, name='delete_report'),
    url(r'^edit-investor/', views.edit_investor, name='edit_investor'),
    url(r'^messages_home/', views.messages_home, name='messages_home'),
    url(r'^messages_from/', views.messages_from, name='messages_from'),
    url(r'^add_project/', views.add_project, name='add_project'),
    url(r'^remove_project/', views.remove_project, name='remove_project'),
    url(r'^remove_project1/', views.remove_project1, name='remove_project1'),
    url(r'^remove_file/', views.remove_file, name='remove_file'),
    url(r'^remove_file1/', views.remove_file1, name='remove_file1'),
    url(r'^advanced_search/', views.advanced_search, name='advanced_search'),
    url(r'^groups_home/', views.groups_home, name='groups_home'),
    url(r'^create_site_admin/', views.create_site_admin, name='create_site_admin'),
    url(r'^create_report/', views.create_form, name='create_form'),
    url(r'^selected_group/', views.selected_group, name='selected_group'),
    url(r'^remove_self_from_group/', views.remove_self_from_group, name='remove_self_from_group'),
    url(r'^remove_from_group/', views.remove_from_group, name='remove_from_group'),
    url(r'^reports/', views.view_reports, name='view_reports'),
    url(r'^listofreports/', views.report_final, name='final_reports'),
    url(r'^list_all_reports/', views.list_all_reports),
    url(r'^app_report_details/(?P<pk>[0-9]+)/$', views.report_detail),
    url(r'^get_pictures/', views.get_pictures),
    url(r'^login_accepted', views.login_accepted),
    url(r'^list_of_users/', views.list_of_users, name='list_of_users'),
    url(r'^selected_user/', views.selected_user, name='selected_user'),
    url(r'^ban_user/', views.ban_user, name='ban_user'),
    url(r'^decrypted_message', views.decrypted_message, name='decrypted_message'),
    url(r'^index/', views.create_site_admin),
    url(r'^banned/', views.investor),
    url(r'^delete_message/', views.delete_message, name='delete_message'),
    url(r'^list/', views.list, name=""),
]
